# Generated by Django 5.2.17 on 2026-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0001_initial'),
        ('users_module', '0007_deactivate_legacy_school_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='target_grades',
            field=models.ManyToManyField(blank=True, help_text='اگر هر سه محدوده خالی باشند، خبر برای همه قابل مشاهده است.', related_name='targeted_news_articles', to='users_module.grade', verbose_name='پایه\u200cهای مخاطب'),
        ),
        migrations.AddField(
            model_name='article',
            name='target_provinces',
            field=models.ManyToManyField(blank=True, help_text='در صورت خالی بودن، خبر از نظر استان محدود نمی\u200cشود.', related_name='targeted_news_articles', to='users_module.province', verbose_name='استان\u200cهای مخاطب'),
        ),
        migrations.AddField(
            model_name='article',
            name='target_schools',
            field=models.ManyToManyField(blank=True, help_text='در صورت خالی بودن، خبر از نظر مدرسه محدود نمی\u200cشود.', related_name='targeted_news_articles', to='users_module.school', verbose_name='مدارس مخاطب'),
        ),
    ]
