# Generated by Django 5.2.17 on 2026-09-08 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
        ('users_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceTrustee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'معتمد استان',
                'verbose_name_plural': 'معتمدان استان\u200cها',
            },
        ),
        migrations.AlterModelOptions(
            name='consultant',
            options={'verbose_name': 'محدوده دسترسی مشاور', 'verbose_name_plural': 'محدوده\u200cهای دسترسی مشاوران'},
        ),
        migrations.AddField(
            model_name='consultant',
            name='can_answer_psychology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultant',
            name='can_answer_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultant',
            name='can_create_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultant',
            name='can_manage_question_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultant',
            name='can_upload_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultant',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_module.fieldofstudy'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'پسر'), ('FEMALE', 'دختر')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_module.grade'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_module.province'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_module.school'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_module.subject'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='accesses',
            field=models.ManyToManyField(blank=True, to='users_module.access'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='consultant',
            index=models.Index(fields=['consultant', 'subject'], name='auth_module_consult_8e451c_idx'),
        ),
        migrations.AddIndex(
            model_name='consultant',
            index=models.Index(fields=['province', 'school', 'grade'], name='auth_module_provinc_3b5233_idx'),
        ),
        migrations.AddField(
            model_name='provincetrustee',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustees', to='users_module.province'),
        ),
        migrations.AddField(
            model_name='provincetrustee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustee_provinces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='provincetrustee',
            constraint=models.UniqueConstraint(fields=('user', 'province'), name='unique_trustee_per_province'),
        ),
    ]
