# Generated by Django 6.1 on 2026-09-08 07:43

from django.db import migrations, models


def copy_consultant_accesses(apps, schema_editor):
    Consultant = apps.get_model('auth_module', 'Consultant')
    for scope in Consultant.objects.prefetch_related('accesses').iterator(chunk_size=200):
        scope.consultant.accesses.add(*scope.accesses.all())


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
        ('users_module', '0002_alter_access_options_alter_access_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accesses',
            field=models.ManyToManyField(blank=True, help_text='برای کاربران غیر دانش\u200cآموز، دسترسی\u200cهای مجاز را انتخاب کنید.', related_name='users', to='users_module.access', verbose_name='دسترسی\u200cها'),
        ),
        migrations.RunPython(copy_consultant_accesses, migrations.RunPython.noop),
    ]
