# Generated by Django 6.1 on 2026-09-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_provincetrustee_alter_consultant_options_and_more'),
        ('auth_module', '0002_user_accesses'),
    ]

    operations = [
    ]
