# Generated by Django 5.2.17 on 2026-09-08 12:34

from django.db import migrations, models


def copy_legacy_permissions_to_accesses(apps, schema_editor):
    """مجوزهای بولی قدیمیِ دارای درس را پیش از حذف به Access منتقل می‌کند."""
    Consultant = apps.get_model('auth_module', 'Consultant')
    Access = apps.get_model('users_module', 'Access')
    permission_fields = {
        'can_answer_tickets': 'ticket',
        'can_manage_question_bank': 'bank',
        'can_create_exam': 'quiz',
        'can_upload_course': 'course',
    }

    for consultant in Consultant.objects.exclude(subject_id=None):
        for field_name, access_name in permission_fields.items():
            if not getattr(consultant, field_name):
                continue
            access = Access.objects.filter(
                name=access_name, subject_id=consultant.subject_id
            ).first()
            if access is None:
                access = Access.objects.create(
                    name=access_name, subject_id=consultant.subject_id
                )
            consultant.accesses.add(access)


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_provincetrustee_alter_consultant_options_and_more'),
        ('users_module', '0002_alter_access_options_remove_fieldofstudy_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consultant',
            name='auth_module_consult_8e451c_idx',
        ),
        migrations.RemoveIndex(
            model_name='consultant',
            name='auth_module_provinc_3b5233_idx',
        ),
        migrations.RunPython(
            copy_legacy_permissions_to_accesses,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='can_answer_tickets',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='can_create_exam',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='can_manage_question_bank',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='can_upload_course',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='field',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='province',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='school',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_code',
        ),
        migrations.AddIndex(
            model_name='consultant',
            index=models.Index(fields=['consultant'], name='auth_module_consult_411e56_idx'),
        ),
    ]
