# Generated by Django 5.2.17 on 2026-09-09 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_remove_consultant_auth_module_consult_8e451c_idx_and_more'),
        ('users_module', '0003_alter_access_options_fieldofstudy_code_grade_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consultant',
            name='auth_module_consult_411e56_idx',
        ),
        migrations.AddField(
            model_name='consultant',
            name='can_answer_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultant',
            name='can_create_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultant',
            name='can_manage_question_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultant',
            name='can_upload_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultant',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_module.fieldofstudy'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'پسر'), ('FEMALE', 'دختر')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_module.grade'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_module.province'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_module.school'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_module.subject'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='consultant',
            index=models.Index(fields=['consultant', 'subject'], name='auth_module_consult_8e451c_idx'),
        ),
        migrations.AddIndex(
            model_name='consultant',
            index=models.Index(fields=['province', 'school', 'grade'], name='auth_module_provinc_3b5233_idx'),
        ),
    ]
