# Generated by Django 5.2.17 on 2026-09-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_merge_20260908_1210'),
        ('auth_module', '0004_remove_consultant_auth_module_consult_411e56_idx_and_more'),
    ]

    operations = [
    ]
