# Generated by Django 5.2.17 on 2026-09-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0005_merge_20260914_2313'),
        ('users_module', '0005_alter_access_options_remove_fieldofstudy_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consultant',
            name='auth_module_consult_8e451c_idx',
        ),
        migrations.RemoveIndex(
            model_name='consultant',
            name='auth_module_provinc_3b5233_idx',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='can_answer_tickets',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='can_create_exam',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='can_manage_question_bank',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='can_upload_course',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='field',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='province',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='school',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_code',
        ),
        migrations.AddIndex(
            model_name='consultant',
            index=models.Index(fields=['consultant'], name='auth_module_consult_411e56_idx'),
        ),
    ]
