# Generated by Django 5.2.17 on 2026-08-23 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('icon', models.CharField(default='fa-graduation-cap', max_length=50, verbose_name='کلاس آیکون FontAwesome')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات مختصر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('target_field', models.CharField(max_length=100, verbose_name='رشته یا مقطع مدنظر')),
                ('message', models.TextField(blank=True, verbose_name='پیام / درخواست مشاوره')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_called', models.BooleanField(default=False, verbose_name='تماس گرفته شد؟')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='پرسش')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('specialty', models.CharField(max_length=150, verbose_name='تخصص / سمت تحصیلی')),
                ('bio', models.TextField(verbose_name='بیوگرافی مختصر')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='تصویر پروفایل')),
            ],
            options={
                'verbose_name': 'استاد / مشاور',
                'verbose_name_plural': 'اساتید و مشاوران',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='نام دانشجو')),
                ('major_or_rank', models.CharField(max_length=150, verbose_name='رشته / رتبه یا قبولی')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز (از ۵)')),
            ],
            options={
                'verbose_name': 'نظر دانشجو',
                'verbose_name_plural': 'نظرات دانشجویان',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('level', models.CharField(choices=[('konkur', 'کنکور و کارشناسی'), ('arshad', 'کارشناسی ارشد'), ('phd', 'دکتری و پژوهش'), ('skill', 'مهارت\u200cمحور')], default='konkur', max_length=20, verbose_name='سطح تحصیلی')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانشجویان')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='امتیاز')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش در ویژه لندینگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='landing_module.category', verbose_name='دسته\u200cبندی')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='landing_module.instructor', verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'دوره تحصیلی',
                'verbose_name_plural': 'دوره\u200cهای تحصیلی',
            },
        ),
    ]
