# Generated by Django 6.1 on 2026-08-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('message', models.TextField(blank=True, verbose_name='توضیحات یا درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_checked', models.BooleanField(default=False, verbose_name='بررسی شده؟')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره / تماس',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره و تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اصلی')),
                ('subtitle', models.CharField(max_length=300, verbose_name='زیرعنوان / شعار')),
                ('description', models.TextField(verbose_name='متن توضیحات')),
                ('primary_button_text', models.CharField(default='شروع یادگیری', max_length=50, verbose_name='متن دکمه اصلی')),
                ('primary_button_url', models.CharField(default='/auth/register/', max_length=200, verbose_name='لینک دکمه اصلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'بنر اصلی لندینگ',
                'verbose_name_plural': 'بنرهای اصلی لندینگ',
            },
        ),
        migrations.CreateModel(
            name='LandingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='متن سؤال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سؤال متداول',
                'verbose_name_plural': 'سؤالات متداول',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LandingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان ویژگی')),
                ('description', models.TextField(verbose_name='توضیحات مختصر')),
                ('icon', models.CharField(default='fa-solid fa-graduation-cap', help_text='کلاس آیکون Font Awesome مانند: fa-solid fa-book-open', max_length=100, verbose_name='کلاس آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ویژگی پلتفرم',
                'verbose_name_plural': 'ویژگی\u200cهای پلتفرم',
                'ordering': ['order', '-id'],
            },
        ),
    ]
