# Generated by Django 6.1 on 2026-08-22 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('icon', models.CharField(default='fa-graduation-cap', max_length=50, verbose_name='کلاس آیکون FontAwesome')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات مختصر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دوره')),
                ('level', models.CharField(choices=[('konkur', 'کنکور و کارشناسی'), ('arshad', 'کارشناسی ارشد'), ('phd', 'دکتری و پژوهش'), ('skill', 'مهارت\u200cمحور')], default='konkur', max_length=20, verbose_name='سطح تحصیلی')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانشجویان')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='امتیاز')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش در ویژه لندینگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='landing_module.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دوره تحصیلی',
                'verbose_name_plural': 'دوره\u200cهای تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='پرسش')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('specialty', models.CharField(max_length=150, verbose_name='تخصص / سمت تحصیلی')),
                ('bio', models.TextField(verbose_name='بیوگرافی مختصر')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='تصویر پروفایل')),
            ],
            options={
                'verbose_name': 'استاد / مشاور',
                'verbose_name_plural': 'اساتید و مشاوران',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='نام دانشجو')),
                ('major_or_rank', models.CharField(max_length=150, verbose_name='رشته / رتبه یا قبولی')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز (از ۵)')),
            ],
            options={
                'verbose_name': 'نظر دانشجو',
                'verbose_name_plural': 'نظرات دانشجویان',
            },
        ),
        migrations.DeleteModel(
            name='HeroBanner',
        ),
        migrations.DeleteModel(
            name='LandingFAQ',
        ),
        migrations.DeleteModel(
            name='LandingFeature',
        ),
        migrations.AlterModelOptions(
            name='consultationrequest',
            options={'verbose_name': 'درخواست مشاوره', 'verbose_name_plural': 'درخواست\u200cهای مشاوره'},
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='is_called',
            field=models.BooleanField(default=False, verbose_name='تماس گرفته شد؟'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='target_field',
            field=models.CharField(default=100, max_length=100, verbose_name='رشته یا مقطع مدنظر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='پیام / درخواست مشاوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='landing_module.instructor', verbose_name='مدرس'),
        ),
    ]
