# Generated by Django 5.2.17 on 2026-10-03 13:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_module', '0007_deactivate_legacy_school_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='نام مبحث / درس')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ (URL)')),
                ('description', models.TextField(verbose_name='توضیحات دوره')),
                ('learning_outcomes', models.TextField(blank=True, verbose_name='دستاوردهای یادگیری')),
                ('prerequisites', models.TextField(blank=True, verbose_name='پیش\u200cنیازها')),
                ('level', models.CharField(choices=[('BEGINNER', 'مقدماتی'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'پیشرفته'), ('ALL', 'مناسب همه سطوح')], default='ALL', max_length=20, verbose_name='سطح دوره')),
                ('estimated_duration', models.CharField(blank=True, max_length=100, verbose_name='مدت تقریبی دوره')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت دوره')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='تصویر کاور')),
                ('all_fields_allowed', models.BooleanField(default=False, verbose_name='همه رشته\u200cها مجازند')),
                ('all_grades_allowed', models.BooleanField(default=False, verbose_name='همه پایه\u200cها مجازند')),
                ('all_provinces_allowed', models.BooleanField(default=True, verbose_name='همه استان\u200cها مجازند')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('approval_status', models.CharField(choices=[('PENDING', 'در انتظار تأیید'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت تأیید')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('allowed_cities', models.ManyToManyField(blank=True, related_name='courses_allowed_cities', to='users_module.school', verbose_name='شهرهای مجاز')),
                ('allowed_fields', models.ManyToManyField(blank=True, related_name='courses_allowed_fields', to='users_module.fieldofstudy', verbose_name='رشته\u200cهای مجاز')),
                ('allowed_grades', models.ManyToManyField(blank=True, related_name='courses_allowed_grades', to='users_module.grade', verbose_name='پایه\u200cهای مجاز')),
                ('allowed_provinces', models.ManyToManyField(blank=True, related_name='courses_allowed_provinces', to='users_module.province', verbose_name='استان\u200cهای مجاز')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='مدرس / سازنده')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_courses', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('subjects', models.ManyToManyField(blank=True, related_name='courses', to='users_module.subject', verbose_name='درس\u200cها')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='اولین مشاهده')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین مشاهده')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد مشاهده')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses_module.course', verbose_name='دوره')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام دوره',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses_module.course', verbose_name='دوره')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'امتیاز دوره',
                'verbose_name_plural': 'امتیازهای دوره\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان محتوا')),
                ('resource_type', models.CharField(choices=[('video', 'ویدیو'), ('image', 'تصویر'), ('pdf', 'PDF')], max_length=10, verbose_name='نوع محتوا')),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/resources/', verbose_name='فایل محتوا')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='لینک محتوا')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses_module.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'محتوای دوره',
                'verbose_name_plural': 'محتواهای دوره',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سرفصل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات سرفصل')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses_module.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'سرفصل',
                'verbose_name_plural': 'سرفصل\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان جلسه / فایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات جلسه')),
                ('file_type', models.CharField(choices=[('video', 'ویدیو'), ('pdf', 'سند یا جزوه PDF'), ('audio', 'فایل صوتی پادکست'), ('archive', 'فایل فشرده (ZIP)'), ('other', 'سایر موارد')], default='video', max_length=20, verbose_name='نوع محتوا')),
                ('file', models.FileField(blank=True, help_text='در صورت عدم آپلود فایل، لینک محتوا را وارد کنید.', null=True, upload_to='courses/files/', verbose_name='فایل ضمیمه')),
                ('url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='لینک مستقیم یا آنلاین محتوا')),
                ('duration_or_pages', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدت یا تعداد صفحات')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='courses_module.coursesection', verbose_name='سرفصل')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='courses_module.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['approval_status', 'is_active', 'start_date'], name='courses_mod_approva_dfba8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='unique_course_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='courserating',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='unique_course_rating'),
        ),
        migrations.AddConstraint(
            model_name='courserating',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 1), ('value__lte', 5)), name='rating_between_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='courseview',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_course_viewer'),
        ),
    ]
