# Generated by Django 5.2.17 on 2026-09-08 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('topic', models.CharField(max_length=255, verbose_name='نام مبحث / درس')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ (URL)')),
                ('description', models.TextField(verbose_name='توضیحات دوره')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='تصویر کاور')),
                ('all_fields_allowed', models.BooleanField(default=False, verbose_name='همه رشته\u200cها مجازند')),
                ('all_grades_allowed', models.BooleanField(default=False, verbose_name='همه پایه\u200cها مجازند')),
                ('all_provinces_allowed', models.BooleanField(default=False, verbose_name='همه استان\u200cها مجازند')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و ساعت شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت پایان (خالی = دائمی)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / نمایش در سامانه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('allowed_fields', models.ManyToManyField(blank=True, to='users_module.fieldofstudy', verbose_name='رشته\u200cهای مجاز')),
                ('allowed_grades', models.ManyToManyField(blank=True, to='users_module.grade', verbose_name='پایه\u200cهای مجاز')),
                ('allowed_provinces', models.ManyToManyField(blank=True, to='users_module.province', verbose_name='استان\u200cهای مجاز')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='مدرس / سازنده')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سرفصل')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses_module.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'سرفصل',
                'verbose_name_plural': 'سرفصل\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان جلسه / فایل')),
                ('file_type', models.CharField(choices=[('video', 'ویدیو'), ('pdf', 'سند یا جزوه PDF'), ('audio', 'فایل صوتی پادکست'), ('archive', 'فایل فشرده (ZIP)'), ('other', 'سایر موارد')], default='video', max_length=20, verbose_name='نوع محتوا')),
                ('file', models.FileField(upload_to='courses/files/', verbose_name='فایل ضمیمه')),
                ('duration_or_pages', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدت یا تعداد صفحات')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='courses_module.coursesection', verbose_name='سرفصل')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['order'],
            },
        ),
    ]
