# Generated by Django 5.2.17 on 2026-09-08 10:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_existing_courses(apps, schema_editor):
    Course = apps.get_model('courses_module', 'Course')
    Course.objects.all().update(approval_status='APPROVED')


class Migration(migrations.Migration):

    dependencies = [
        ('courses_module', '0001_initial'),
        ('users_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'در انتظار تأیید'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت تأیید'),
        ),
        migrations.RunPython(approve_existing_courses, migrations.RunPython.noop),
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='مدت تقریبی دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, verbose_name='دستاوردهای یادگیری'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'مقدماتی'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'پیشرفته'), ('ALL', 'مناسب همه سطوح')], default='ALL', max_length=20, verbose_name='سطح دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, verbose_name='پیش\u200cنیازها'),
        ),
        migrations.AddField(
            model_name='course',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='دلیل رد'),
        ),
        migrations.AddField(
            model_name='course',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی'),
        ),
        migrations.AddField(
            model_name='course',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_courses', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده'),
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='courses', to='users_module.subject', verbose_name='درس\u200cها'),
        ),
        migrations.AlterField(
            model_name='course',
            name='all_provinces_allowed',
            field=models.BooleanField(default=True, verbose_name='همه استان\u200cها مجازند'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام مبحث / درس'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses_module.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('course', 'student'), name='unique_course_enrollment')],
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses_module.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'student'), name='unique_course_rating'), models.CheckConstraint(condition=models.Q(('value__gte', 1), ('value__lte', 5)), name='rating_between_1_and_5')],
            },
        ),
    ]
