# Generated by Django 5.2.17 on 2026-09-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_module', '0002_course_approval_status_course_capacity_and_more'),
        ('users_module', '0003_alter_access_options_fieldofstudy_code_grade_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='allowed_fields',
            field=models.ManyToManyField(blank=True, related_name='courses_allowed_fields', to='users_module.fieldofstudy', verbose_name='رشته\u200cهای مجاز'),
        ),
        migrations.AlterField(
            model_name='course',
            name='allowed_grades',
            field=models.ManyToManyField(blank=True, related_name='courses_allowed_grades', to='users_module.grade', verbose_name='پایه\u200cهای مجاز'),
        ),
        migrations.AlterField(
            model_name='course',
            name='allowed_provinces',
            field=models.ManyToManyField(blank=True, related_name='courses_allowed_provinces', to='users_module.province', verbose_name='استان\u200cهای مجاز'),
        ),
    ]
