# Generated by Django 6.1 on 2026-09-07 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام فصل')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام درس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions_module.category', verbose_name='دسته'),
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions_module.chapter', verbose_name='فصل'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='questions_module.course', verbose_name='درس'),
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='مهلت زمانی')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='تعداد کل سوالات')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='تعداد درست')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نادرست')),
                ('unanswered_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نزده')),
                ('percent', models.FloatField(default=0.0, verbose_name='درصد')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('done', 'پایان یافته')], default='in_progress', max_length=20, verbose_name='وضعیت')),
                ('auto_submitted', models.BooleanField(default=False, verbose_name='ثبت خودکار (اتمام زمان)')),
                ('chapters', models.ManyToManyField(related_name='exam_sessions', to='questions_module.chapter', verbose_name='فصل\u200cها')),
                ('questions', models.ManyToManyField(related_name='exam_sessions', to='questions_module.question', verbose_name='سوالات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'جلسه آزمون',
                'verbose_name_plural': 'جلسات آزمون',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='تعداد کل سوالات')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='تعداد درست')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نادرست')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نزده')),
                ('percent', models.FloatField(default=0.0, verbose_name='درصد')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('done', 'پایان یافته')], default='in_progress', max_length=20, verbose_name='وضعیت')),
                ('chapters', models.ManyToManyField(related_name='practice_sessions', to='questions_module.chapter', verbose_name='فصل\u200cها')),
                ('questions', models.ManyToManyField(related_name='practice_sessions', to='questions_module.question', verbose_name='سوالات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'جلسه تمرین',
                'verbose_name_plural': 'جلسات تمرین',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'name')},
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='پاسخ درست')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='زمان پاسخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions_module.question', verbose_name='سوال')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questions_module.choice', verbose_name='گزینه انتخابی')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions_module.examsession', verbose_name='جلسه آزمون')),
            ],
            options={
                'verbose_name': 'پاسخ آزمون',
                'verbose_name_plural': 'پاسخ\u200cهای آزمون',
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.CreateModel(
            name='PracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='پاسخ درست')),
                ('revealed', models.BooleanField(default=False, verbose_name='مشاهده جواب')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='زمان پاسخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions_module.question', verbose_name='سوال')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questions_module.choice', verbose_name='گزینه انتخابی')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions_module.practicesession', verbose_name='جلسه تمرین')),
            ],
            options={
                'verbose_name': 'پاسخ تمرین',
                'verbose_name_plural': 'پاسخ\u200cهای تمرین',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
