# Generated by Django 6.1 on 2026-09-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0002_chapter_course_alter_question_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='requested_difficulty',
            field=models.CharField(blank=True, choices=[('E', 'ساده'), ('M', 'متوسط'), ('H', 'سخت'), ('VH', 'خیلی سخت')], max_length=2, verbose_name='سطح انتخابی'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='requested_difficulty',
            field=models.CharField(blank=True, choices=[('E', 'ساده'), ('M', 'متوسط'), ('H', 'سخت'), ('VH', 'خیلی سخت')], max_length=2, verbose_name='سطح انتخابی'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای')], default='MCQ', max_length=3, verbose_name='نوع سوال'),
        ),
    ]
