# Generated by Django 6.1 on 2026-09-08 07:43

import django.db.models.deletion
from django.db import migrations, models


def connect_legacy_courses_to_subjects(apps, schema_editor):
    Chapter = apps.get_model('questions_module', 'Chapter')
    Subject = apps.get_model('users_module', 'Subject')
    for chapter in Chapter.objects.select_related('course').filter(course__isnull=False):
        subject = Subject.objects.filter(title=chapter.course.name).order_by('pk').first()
        if subject:
            chapter.subject = subject
            chapter.save(update_fields=['subject'])


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0003_examsession_requested_difficulty_and_more'),
        ('users_module', '0002_alter_access_options_alter_access_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['subject__title', 'name'], 'verbose_name': 'فصل', 'verbose_name_plural': 'فصل\u200cها'},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_chapters', to='users_module.subject', verbose_name='درس ثبت\u200cشده'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='questions_module.course', verbose_name='درس'),
        ),
        migrations.RunPython(connect_legacy_courses_to_subjects, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('subject', 'name'), name='unique_chapter_per_subject'),
        ),
    ]
