# Generated by Django 6.1 on 2026-09-08 12:30

import django.core.validators
import questions_module.models
from django.db import migrations, models


def merge_very_hard_into_hard(apps, schema_editor):
    Question = apps.get_model('questions_module', 'Question')
    PracticeSession = apps.get_model('questions_module', 'PracticeSession')
    ExamSession = apps.get_model('questions_module', 'ExamSession')
    Question.objects.filter(difficulty='VH').update(difficulty='H')
    PracticeSession.objects.filter(requested_difficulty='VH').update(requested_difficulty='H')
    ExamSession.objects.filter(requested_difficulty='VH').update(requested_difficulty='H')


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0004_alter_chapter_options_alter_chapter_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, upload_to='questions/choice_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), questions_module.models.validate_question_image_size], verbose_name='تصویر گزینه'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='questions/question_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), questions_module.models.validate_question_image_size], verbose_name='تصویر سوال'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, max_length=255, verbose_name='متن گزینه'),
        ),
        migrations.RunPython(merge_very_hard_into_hard, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='examsession',
            name='requested_difficulty',
            field=models.CharField(blank=True, choices=[('E', 'آسان'), ('M', 'متوسط'), ('H', 'دشوار')], max_length=2, verbose_name='سطح انتخابی'),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='requested_difficulty',
            field=models.CharField(blank=True, choices=[('E', 'آسان'), ('M', 'متوسط'), ('H', 'دشوار')], max_length=2, verbose_name='سطح انتخابی'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('E', 'آسان'), ('M', 'متوسط'), ('H', 'دشوار')], default='M', max_length=2, verbose_name='سطح دشواری'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, verbose_name='متن سوال'),
        ),
    ]
