# Generated by Django 6.1 on 2026-09-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0005_choice_image_question_image_alter_choice_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='difficulty_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='ترکیب سطح سؤال\u200cها'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='difficulty_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='ترکیب سطح سؤال\u200cها'),
        ),
    ]
