# Generated by Django 6.1 on 2026-09-08 13:35

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0006_examsession_difficulty_breakdown_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='approval_note',
            field=models.TextField(blank=True, verbose_name='یادداشت تأیید/رد'),
        ),
        migrations.AddField(
            model_name='question',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='approved', max_length=20, verbose_name='وضعیت تأیید'),
        ),
        migrations.AddField(
            model_name='question',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی'),
        ),
        migrations.AddField(
            model_name='question',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_questions', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='متن گزینه'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='پاسخ تشریحی'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='متن سوال'),
        ),
    ]
