# Generated by Django 6.1 on 2026-09-09 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0007_question_approval_note_question_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای'), ('ESS', 'تشریحی')], default='MCQ', max_length=3, verbose_name='نوع سؤال'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای'), ('ESS', 'تشریحی')], default='MCQ', max_length=3, verbose_name='نوع سؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای'), ('ESS', 'تشریحی')], default='MCQ', max_length=3, verbose_name='نوع سوال'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مبحث')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='questions_module.chapter', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'مبحث',
                'verbose_name_plural': 'مباحث',
                'ordering': ['chapter__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions_module.topic', verbose_name='مبحث'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('chapter', 'name'), name='unique_topic_per_chapter'),
        ),
    ]
