# Generated by Django 6.1 on 2026-09-16 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0008_examsession_question_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['chapter__subject__title', 'chapter__name', 'name'], 'verbose_name': 'مبحث', 'verbose_name_plural': 'مباحث'},
        ),
        migrations.AddField(
            model_name='examanswer',
            name='text_answer',
            field=models.TextField(blank=True, verbose_name='پاسخ تشریحی کاربر'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='exam_sessions', to='questions_module.topic', verbose_name='مباحث'),
        ),
        migrations.AddField(
            model_name='practiceanswer',
            name='text_answer',
            field=models.TextField(blank=True, verbose_name='پاسخ تشریحی کاربر'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='practice_sessions', to='questions_module.topic', verbose_name='مباحث'),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای'), ('DES', 'تشریحی')], default='MCQ', max_length=3, verbose_name='نوع سؤال'),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای'), ('DES', 'تشریحی')], default='MCQ', max_length=3, verbose_name='نوع سؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای'), ('DES', 'تشریحی')], default='MCQ', max_length=3, verbose_name='نوع سوال'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='questions_module.chapter', verbose_name='فصل'),
        ),
    ]
