# Generated by Django 5.2.17 on 2026-09-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0008_examsession_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='practicesession',
            name='question_type',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای')], default='MCQ', max_length=3, verbose_name='نوع سوال'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
