# Generated by Django 5.2.17 on 2026-09-16 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0009_remove_question_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='text_answer',
            field=models.TextField(blank=True, verbose_name='پاسخ تشریحی کاربر'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای'), ('DES', 'تشریحی')], default='MCQ', max_length=3, verbose_name='نوع سؤال'),
        ),
        migrations.AddField(
            model_name='practiceanswer',
            name='text_answer',
            field=models.TextField(blank=True, verbose_name='پاسخ تشریحی کاربر'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای'), ('DES', 'تشریحی')], default='MCQ', max_length=3, verbose_name='نوع سؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای'), ('DES', 'تشریحی')], default='MCQ', max_length=3, verbose_name='نوع سوال'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مبحث')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='questions_module.chapter', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'مبحث',
                'verbose_name_plural': 'مباحث',
                'ordering': ['chapter__subject__title', 'chapter__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='examsession',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='exam_sessions', to='questions_module.topic', verbose_name='مباحث'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='practice_sessions', to='questions_module.topic', verbose_name='مباحث'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions_module.topic', verbose_name='مبحث'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('chapter', 'name'), name='unique_topic_per_chapter'),
        ),
    ]
