# Generated by Django 5.2.17 on 2026-09-08 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_legacy_approvals(apps, schema_editor):
    TicketMessage = apps.get_model('ticketing_module', 'TicketMessage')
    TicketMessage.objects.filter(is_approved_by_moderator=True).update(
        moderation_status='APPROVED'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_provincetrustee_alter_consultant_options_and_more'),
        ('ticketing_module', '0001_initial'),
        ('users_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-updated_at'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='ticketauditlog',
            options={'ordering': ['created_at'], 'verbose_name': 'رویداد تیکت', 'verbose_name_plural': 'گردش تیکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'پیام تیکت', 'verbose_name_plural': 'پیام\u200cهای تیکت'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='current_assignee_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='current_queue',
            field=models.CharField(choices=[('MODERATOR', 'ناظر محتوا'), ('CONSULTANT', 'مشاور'), ('TRUSTEE', 'معتمد استان'), ('ADMIN', 'مدیر سیستم')], default='MODERATOR', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketauditlog',
            name='from_queue',
            field=models.CharField(blank=True, choices=[('MODERATOR', 'ناظر محتوا'), ('CONSULTANT', 'مشاور'), ('TRUSTEE', 'معتمد استان'), ('ADMIN', 'مدیر سیستم')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketauditlog',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_referrals_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketauditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ticketauditlog',
            name='to_queue',
            field=models.CharField(blank=True, choices=[('MODERATOR', 'ناظر محتوا'), ('CONSULTANT', 'مشاور'), ('TRUSTEE', 'معتمد استان'), ('ADMIN', 'مدیر سیستم')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticketauditlog',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_referrals_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='یادداشت داخلی برای عوامل سامانه و غیرقابل نمایش به دانش\u200cآموز'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=10),
        ),
        migrations.RunPython(preserve_legacy_approvals, migrations.RunPython.noop),
        migrations.AddField(
            model_name='ticketmessage',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ticket_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'در انتظار تأیید ناظر'), ('OPEN', 'باز'), ('IN_PROGRESS', 'در حال پیگیری'), ('RESOLVED', 'پاسخ داده شده'), ('CLOSED', 'بسته شده')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'ایجاد تیکت'), ('MESSAGE_SENT', 'ارسال پیام'), ('APPROVED', 'تأیید محتوا'), ('REJECTED', 'رد محتوا'), ('REFERRED', 'ارجاع تیکت'), ('SUBJECT_CHANGED', 'تغییر درس'), ('TYPE_CHANGED', 'تغییر موضوع'), ('STATUS_CHANGED', 'تغییر وضعیت'), ('CLOSED', 'بستن تیکت'), ('REOPENED', 'بازگشایی تیکت')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['current_queue', 'status'], name='ticketing_m_current_07cef8_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_type', 'subject'], name='ticketing_m_ticket__9a1a43_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['moderation_status', 'created_at'], name='ticketing_m_moderat_08fdf4_idx'),
        ),
    ]
