# Generated by Django 5.2.17 on 2026-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_module', '0003_ticket_is_private_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='current_queue',
            field=models.CharField(choices=[('MODERATOR', 'ناظر محتوا'), ('CONSULTANT', 'مشاور'), ('TRUSTEE', 'مسئول منطقه'), ('ADMIN', 'مدیر سیستم')], default='MODERATOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketauditlog',
            name='from_queue',
            field=models.CharField(blank=True, choices=[('MODERATOR', 'ناظر محتوا'), ('CONSULTANT', 'مشاور'), ('TRUSTEE', 'مسئول منطقه'), ('ADMIN', 'مدیر سیستم')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticketauditlog',
            name='to_queue',
            field=models.CharField(blank=True, choices=[('MODERATOR', 'ناظر محتوا'), ('CONSULTANT', 'مشاور'), ('TRUSTEE', 'مسئول منطقه'), ('ADMIN', 'مدیر سیستم')], max_length=20, null=True),
        ),
    ]
