# Generated by Django 6.1 on 2026-09-08 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'دسترسی', 'verbose_name_plural': 'دسترسی\u200cها'},
        ),
        migrations.AlterField(
            model_name='access',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='خالی بودن درس یعنی دسترسی به همه درس\u200cها.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users_module.subject'),
        ),
        migrations.AddConstraint(
            model_name='access',
            constraint=models.UniqueConstraint(fields=('name', 'subject'), name='unique_access_per_subject'),
        ),
    ]
