# Generated by Django 5.2.17 on 2026-09-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'دسترسی', 'verbose_name_plural': 'دسترسی\u200cها'},
        ),
        migrations.RemoveField(
            model_name='fieldofstudy',
            name='code',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
    ]
