# Generated by Django 5.2.17 on 2026-09-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0002_alter_access_options_remove_fieldofstudy_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={},
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='code',
            field=models.CharField(default=' ', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='code',
            field=models.CharField(default=' ', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default=' ', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
