# Generated by Django 5.2.17 on 2026-09-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0003_access_creation_permissions'),
        ('users_module', '0003_alter_access_options_fieldofstudy_code_grade_code_and_more'),
    ]

    operations = [
    ]
