# Generated by Django 5.2.17 on 2026-09-15 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0004_merge_20260914_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={},
        ),
        migrations.RemoveField(
            model_name='fieldofstudy',
            name='code',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.AlterField(
            model_name='access',
            name='name',
            field=models.CharField(choices=[('bank', 'بانک سوال'), ('ticket', 'تیکت'), ('quiz', 'آزمون'), ('course', 'دوره'), ('create_question', 'ثبت سوال'), ('edit_question', 'ویرایش سوال'), ('delete_question', 'حذف سوال'), ('create_chapter', 'ایجاد فصل'), ('create_subject', 'ایجاد درس')], max_length=200),
        ),
        migrations.AlterField(
            model_name='access',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_module.subject'),
        ),
    ]
