# Generated by Django 5.2.17 on 2026-09-15 20:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_module', '0006_remove_consultant_auth_module_consult_8e451c_idx_and_more'),
        ('users_module', '0005_alter_access_options_remove_fieldofstudy_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('SUBJECT', 'مطالعه درس'), ('FREE', 'زمان آزاد'), ('ENTERTAINMENT', 'سرگرمی'), ('LEARNING', 'یادگیری مهارت'), ('REST', 'استراحت'), ('OTHER', 'سایر')], default='SUBJECT', max_length=20, verbose_name='نوع فعالیت')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='عنوان')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه')], verbose_name='روز هفته')),
                ('start_hour', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(23)], verbose_name='ساعت شروع')),
                ('end_hour', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(24)], verbose_name='ساعت پایان')),
                ('color', models.CharField(choices=[('blue', 'آبی'), ('violet', 'بنفش'), ('emerald', 'سبز'), ('amber', 'کهربایی'), ('rose', 'صورتی'), ('cyan', 'فیروزه\u200cای')], default='blue', max_length=12, verbose_name='رنگ')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='یادداشت')),
                ('source', models.CharField(choices=[('SELF', 'برنامه شخصی'), ('CONSULTANT', 'پیشنهاد مشاور'), ('ADMIN', 'برنامه مدیر')], default='SELF', max_length=20, verbose_name='منبع')),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='شناسه تخصیص گروهی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plan_entries', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='auth_module.student', verbose_name='دانش\u200cآموز')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_entries', to='users_module.subject', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'آیتم برنامه',
                'verbose_name_plural': 'آیتم\u200cهای برنامه',
                'ordering': ['weekday', 'start_hour', 'end_hour'],
            },
        ),
        migrations.CreateModel(
            name='PlanCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='شروع هفته')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان انجام')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='plans_module.planentry', verbose_name='آیتم برنامه')),
            ],
            options={
                'verbose_name': 'انجام برنامه',
                'verbose_name_plural': 'انجام\u200cهای برنامه',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='planentry',
            index=models.Index(fields=['student', 'weekday', 'start_hour'], name='plans_modul_student_f07546_idx'),
        ),
        migrations.AddIndex(
            model_name='planentry',
            index=models.Index(fields=['assigned_by', 'source'], name='plans_modul_assigne_e29b5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='planentry',
            constraint=models.CheckConstraint(condition=models.Q(('start_hour__gte', 8), ('start_hour__lte', 23)), name='plan_start_hour_between_8_23'),
        ),
        migrations.AddConstraint(
            model_name='planentry',
            constraint=models.CheckConstraint(condition=models.Q(('end_hour__gte', 9), ('end_hour__lte', 24)), name='plan_end_hour_between_9_24'),
        ),
        migrations.AddConstraint(
            model_name='planentry',
            constraint=models.CheckConstraint(condition=models.Q(('end_hour__gt', models.F('start_hour'))), name='plan_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='plancompletion',
            constraint=models.UniqueConstraint(fields=('entry', 'week_start'), name='unique_weekly_plan_completion'),
        ),
    ]
