# Generated by Django 5.2.17 on 2026-09-15 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0006_remove_consultant_auth_module_consult_8e451c_idx_and_more'),
        ('plans_module', '0001_initial'),
        ('users_module', '0005_alter_access_options_remove_fieldofstudy_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='planentry',
            name='plans_modul_student_f07546_idx',
        ),
        migrations.AddField(
            model_name='planentry',
            name='scheduled_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='تاریخ اجرا'),
        ),
        migrations.AddIndex(
            model_name='planentry',
            index=models.Index(fields=['student', 'scheduled_date', 'start_hour'], name='plans_modul_student_466d4c_idx'),
        ),
    ]
