# Generated by Django 6.1 on 2026-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست\u200cها'},
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='تاریخ و ساعت انتشار. اگر خالی باشد و وضعیت منتشرشده باشد، همین الان منتشر می\u200cشود. برای زمان\u200cبندی، تاریخ آینده بگذار.', null=True, verbose_name='زمان انتشار'),
        ),
    ]
