# Generated by Django 6.1 on 2026-08-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/content/', verbose_name='عکس داخل پست'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/', verbose_name='فیلم داخل پست'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='posts/covers/', verbose_name='کاور صفحه اصلی'),
        ),
    ]
