# Generated by Django 6.1 on 2026-09-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_count',
            field=models.PositiveIntegerField(default=10, verbose_name='تعداد سؤال'),
        ),
    ]
