# Generated by Django 5.2.17 on 2026-10-03 13:40

import ckeditor_uploader.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_module', '0011_merge_20260922_0100'),
        ('quiz_module', '0002_quiz_question_count'),
        ('users_module', '0007_deactivate_legacy_school_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_hidden', 'خروج از صفحه'), ('tab_visible', 'بازگشت به صفحه')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'آزمون', 'verbose_name_plural': 'آزمون\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='quizchoice',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='all_students',
            field=models.BooleanField(default=False, verbose_name='همه دانش\u200cآموزان'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_release_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار پاسخ\u200cنامه'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='متوقف'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='negative_marking',
            field=models.BooleanField(default=False, verbose_name='نمره منفی'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='negative_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.33'), max_digits=4, verbose_name='ضریب نمره منفی'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='publish_results',
            field=models.BooleanField(default=True, verbose_name='نمایش نتیجه به دانش\u200cآموز'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_choices',
            field=models.BooleanField(default=True, verbose_name='چیدمان تصادفی گزینه\u200cها'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_questions',
            field=models.BooleanField(default=True, verbose_name='چیدمان تصادفی سؤال\u200cها'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='answer_image',
            field=models.ImageField(blank=True, upload_to='quizzes/answers/%Y/%m/', verbose_name='تصویر پاسخ دست\u200cنویس'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_quiz_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='grader_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='saved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='text_answer',
            field=models.TextField(blank=True, verbose_name='پاسخ متنی'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='auto_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='choice_order',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='question_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'در حال انجام'), ('submitted', 'ارسال شده'), ('graded', 'تصحیح شده')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='tab_switch_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='wrong_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='bank_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_quiz_questions', to='questions_module.question'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='bank_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='questions_module.topic', verbose_name='مبحث مرتبط'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='پاسخ تشریحی'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='explanation_image',
            field=models.ImageField(blank=True, upload_to='quizzes/explanations/%Y/%m/', verbose_name='تصویر پاسخ تشریحی'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'چهارگزینه\u200cای'), ('DES', 'تشریحی')], default='MCQ', max_length=3, verbose_name='نوع سؤال'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='source_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_copies', to='questions_module.question'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='submit_to_bank',
            field=models.BooleanField(default=True, verbose_name='ارسال به صف بانک سؤال پس از آزمون'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='closes_at',
            field=models.DateTimeField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='users_module.fieldofstudy'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='users_module.grade'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opens_at',
            field=models.DateTimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='users_module.province'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد سؤال'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='users_module.school'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='quiz_module.quizchoice'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_module.quizquestion'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='متن سؤال'),
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_answer'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(fields=('quiz', 'student', 'started_at'), name='unique_quiz_attempt_start'),
        ),
        migrations.AddField(
            model_name='quizevent',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quiz_module.quizattempt'),
        ),
    ]
